### ISSUE TITLE
WP-BNHM: needs .htaccess file writeable?

### ISSUE THREAD

**Issue by mkoo** [BNHM/CoreServices#3]
If not any more then please add to mod_rewrite rules:

<IfModule mod_rewrite.c>
RewriteEngine On
RewriteBase /wp_bnhm/
RewriteRule ^index\.php$ - [L]
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteRule . /wp_bnhm/index.php [L]
</IfModule>

(I can show you help on wp)

**Comment by mkoo** [comment]
PS. not sure who best to send to!

**Comment by JoyceGross** [comment]
Did you try to create the file? It does not exist and you have write permissions in the directory. 

Ok, I exists now. I went ahead and created it. It's owned by you, so you should be able to edit it.

**Comment by mkoo** [comment]
that explains why I couldnt see it! let me try it out.
thanks
